# Generated by Django 4.2 on 2023-04-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvfile',
            name='name',
        ),
        migrations.AddField(
            model_name='csvfile',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='csvfile',
            name='file_name',
            field=models.CharField(default='Admin', max_length=255, verbose_name='Uploaded By'),
            preserve_default=False,
        ),
    ]
